import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, Bot, Braces, Check, CheckCircle2, ChevronRight, CircleDollarSign, Clipboard, Code2, DatabaseZap, ExternalLink, Fingerprint, Gauge, Layers3, Network, Play, Radar, ScanSearch, Shield, ShieldAlert, Sparkles, TimerReset, Wallet, XCircle, Zap } from 'lucide-react';
import { api } from '@appdeploy/client';

declare global { interface Window { ethereum?: { request: (args: { method: string; params?: unknown[] }) => Promise<unknown> } } }

type Tab = 'analyze' | 'architecture' | 'opportunity';
type Decision = 'ALLOW' | 'REQUIRE_HUMAN' | 'BLOCK';
type Severity = 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
type Finding = { severity: Severity; title: string; detail: string; source: string };
type Analysis = { decision: Decision; riskScore: number; deterministicScore: number; aiScore: number; aiConfidence: number; aiAlignment: string; aiRationale: string; selector: string; selectorLabel: string; rpcStatus: string; networkBlock: string; gasEstimate: string; targetType: string; proxyDetected: boolean; temporalConsistency: string; findings: Finding[]; policy: { maxValueEth: string; allowUnlimitedApprovals: boolean; strictIntent: boolean }; evidenceHash: string };
type FormState = { intent: string; from: string; to: string; valueEth: string; data: string; maxValueEth: string };

const ZERO = '0x0000000000000000000000000000000000000000';
const EOA = '0x1111111111111111111111111111111111111111';
const demoSafe: FormState = { intent: 'Send 0.002 ETH to my known test wallet. No contract call and no token approvals.', from: ZERO, to: EOA, valueEth: '0.002', data: '0x', maxValueEth: '0.01' };
const demoApproval: FormState = { intent: 'Swap up to 100 USDC for ETH. Never grant unlimited approval.', from: ZERO, to: EOA, valueEth: '0', data: '0x095ea7b30000000000000000000000002222222222222222222222222222222222222222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff', maxValueEth: '0.01' };
const demoUnknown: FormState = { intent: 'Interact with a new protocol, but do not give it broad permissions or move assets outside the requested action.', from: ZERO, to: EOA, valueEth: '0', data: '0x123456780000000000000000000000000000000000000000000000000000000000000001', maxValueEth: '0.01' };
const stages = ['Intent', 'Decode', 'Policy', 'Simulate', 'AI review', 'Decision'];

const prettyDecision = (d: Decision) => d === 'REQUIRE_HUMAN' ? 'HUMAN REVIEW' : d;
const shortAddress = (v: string) => v && v.length > 12 ? `${v.slice(0, 7)}…${v.slice(-5)}` : v || '—';

export default function AegisApp() {
  const [tab, setTab] = useState<Tab>('analyze');
  const [form, setForm] = useState<FormState>(demoApproval);
  const [result, setResult] = useState<Analysis | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [scanStep, setScanStep] = useState(0);
  const [copied, setCopied] = useState(false);
  const timerRef = useRef<number | null>(null);

  useEffect(() => () => { if (timerRef.current) window.clearInterval(timerRef.current); }, []);
  const riskLabel = useMemo(() => !result ? '' : result.riskScore >= 80 ? 'Critical exposure' : result.riskScore >= 60 ? 'High exposure' : result.riskScore >= 35 ? 'Review recommended' : 'Low exposure', [result]);
  const setField = (key: keyof FormState, value: string) => setForm(prev => ({ ...prev, [key]: value }));
  const loadDemo = (demo: FormState) => { setForm(demo); setResult(null); setError(''); setScanStep(0); };

  const connectWallet = async () => {
    setError('');
    if (!window.ethereum) { setError('No se detectó una wallet EVM. El analizador manual sigue disponible para la demo.'); return; }
    try { const accounts = await window.ethereum.request({ method: 'eth_requestAccounts' }) as string[]; if (accounts?.[0]) setField('from', accounts[0]); }
    catch { setError('La wallet no autorizó la conexión.'); }
  };

  const runAnalysis = async (payload: FormState = form) => {
    if (timerRef.current) window.clearInterval(timerRef.current);
    setLoading(true); setError(''); setResult(null); setCopied(false); setScanStep(1);
    timerRef.current = window.setInterval(() => setScanStep(step => Math.min(5, step + 1)), 620);
    try { const response = await api.post('/api/analyze', { ...payload, policy: { maxValueEth: payload.maxValueEth, allowUnlimitedApprovals: false, strictIntent: true } }); setResult(response.data as Analysis); setScanStep(6); }
    catch (e) { const message = e instanceof Error ? e.message : 'No se pudo ejecutar el análisis.'; setError(`AEGIS no pudo completar el análisis: ${message}`); }
    finally { if (timerRef.current) window.clearInterval(timerRef.current); timerRef.current = null; setLoading(false); }
  };

  const runRiskDemo = () => { setForm(demoApproval); void runAnalysis(demoApproval); };
  const copyEvidence = async () => { if (!result) return; try { await navigator.clipboard.writeText(result.evidenceHash); setCopied(true); window.setTimeout(() => setCopied(false), 1600); } catch { setCopied(false); } };

  return <div className='app-shell'>
    <header className='topbar'><div className='brand'><div className='brand-mark'><Shield size={18}/></div><div><div className='brand-name'>AEGIS</div><div className='brand-sub'>AUTONOMOUS TRANSACTION FIREWALL</div></div></div><div className='top-actions'><div className='network-pill'><span className='dot'/><Network size={13}/> Arbitrum Sepolia</div><button className='compact-btn' onClick={runRiskDemo}><Zap size={14}/> Live demo</button></div></header>
    <main className='container'>
      <section className='hero'><div className='hero-copy'><div className='eyebrow'><span/> Intent-bound security for AI agents</div><h1>Put a security boundary between <em>AI</em> and <em>money.</em></h1><p>AEGIS entiende lo que autorizó el humano, inspecciona la transacción propuesta, simula ejecución y aplica reglas determinísticas antes de permitir que un agente toque fondos.</p><div className='hero-actions'><button className='btn btn-primary' onClick={runRiskDemo}><Play size={16}/> Ejecutar demo</button><button className='btn btn-secondary' onClick={() => setTab('architecture')}><Layers3 size={16}/> Ver arquitectura</button></div></div><div className='hero-proof'><div className='proof-top'><span>SECURITY PIPELINE</span><span className='live-label'><span className='dot'/> LIVE</span></div><div className='proof-flow'><span>Intent</span><ArrowRight size={14}/><span>Decode</span><ArrowRight size={14}/><span>Simulate</span><ArrowRight size={14}/><b>Enforce</b></div><div className='proof-metrics'><div><strong>0</strong><span>private keys</span></div><div><strong>6</strong><span>defense stages</span></div><div><strong>1</strong><span>final policy</span></div></div></div></section>
      <nav className='tabs' aria-label='AEGIS sections'><button className={`tab ${tab === 'analyze' ? 'active' : ''}`} onClick={() => setTab('analyze')}><ScanSearch size={15}/> Analyze</button><button className={`tab ${tab === 'architecture' ? 'active' : ''}`} onClick={() => setTab('architecture')}><Braces size={15}/> Architecture</button><button className={`tab ${tab === 'opportunity' ? 'active' : ''}`} onClick={() => setTab('opportunity')}><Gauge size={15}/> Opportunity</button></nav>
      {tab === 'analyze' && <><div className='scan-rail'>{stages.map((stage, index) => { const done = scanStep > index; const active = loading && scanStep === index + 1; return <div className={`scan-node ${done ? 'done' : ''} ${active ? 'active' : ''}`} key={stage}><div className='scan-dot'>{done ? <Check size={12}/> : index + 1}</div><span>{stage}</span></div>; })}</div><div className='grid'>
        <section className='panel input-panel'><div className='panel-title'><div><span className='panel-kicker'>PROPOSED ACTION</span><h2>Bind intent to transaction</h2></div><span className='tag'>PRE-SIGN</span></div><div className='demo-row'><button className='demo-chip' onClick={() => loadDemo(demoSafe)}><CheckCircle2 size={13}/> Safe transfer</button><button className='demo-chip danger' onClick={() => loadDemo(demoApproval)}><ShieldAlert size={13}/> Approval risk</button><button className='demo-chip' onClick={() => loadDemo(demoUnknown)}><Code2 size={13}/> Unknown call</button></div><div className='field'><div className='label'>HUMAN INTENT <span>source of truth</span></div><textarea className='textarea intent-input' value={form.intent} onChange={e => setField('intent', e.target.value)} placeholder='What did the user actually authorize?'/></div><div className='field'><div className='label'>FROM</div><div className='wallet-line'><input className='input mono' value={form.from} onChange={e => setField('from', e.target.value)}/><button className='btn btn-secondary wallet-btn' onClick={connectWallet}><Wallet size={15}/>Wallet</button></div></div><div className='field'><div className='label'>TO</div><input className='input mono' value={form.to} onChange={e => setField('to', e.target.value)}/></div><div className='row'><div className='field'><div className='label'>VALUE · ETH</div><input className='input' value={form.valueEth} onChange={e => setField('valueEth', e.target.value)}/></div><div className='field'><div className='label'>POLICY MAX · ETH</div><input className='input' value={form.maxValueEth} onChange={e => setField('maxValueEth', e.target.value)}/></div></div><div className='field'><div className='label'>CALLDATA <span>{form.data.length > 10 ? form.data.slice(0, 10) : 'native'}</span></div><textarea className='textarea mono calldata' value={form.data} onChange={e => setField('data', e.target.value)} spellCheck={false}/></div><div className='actions'><button className='btn btn-primary analyze-btn' onClick={() => void runAnalysis()} disabled={loading}>{loading ? <><Radar className='spin' size={16}/> Running security pipeline…</> : <><ScanSearch size={16}/> Analyze before signing</>}</button><span className='privacy-note'><Fingerprint size={13}/> No keys, no signing, no custody.</span></div>{error && <div className='error-box' role='alert'><AlertTriangle size={16}/><span>{error}</span></div>}</section>
        <section className='panel result-panel'><div className='panel-title'><div><span className='panel-kicker'>POLICY ENGINE</span><h2>Decision</h2></div><span className='tag'>AI ≠ AUTHORITY</span></div>{loading && <LoadingState step={scanStep}/>} {!loading && !result && <div className='empty'><div className='empty-orbit'><Shield size={34}/></div><h3>Ready to inspect</h3><p>Ejecuta el demo para ver cómo AEGIS compara intención, permisos y evidencia de ejecución.</p><button className='text-action' onClick={runRiskDemo}>Run demo <ChevronRight size={14}/></button></div>}{!loading && result && <ResultView result={result} riskLabel={riskLabel} copied={copied} onCopy={copyEvidence}/>}</section>
      </div></>}
      {tab === 'architecture' && <Architecture/>}{tab === 'opportunity' && <Opportunity/>}
    </main><footer className='footer'><div><Shield size={14}/> AEGIS MVP · built for Arbitrum</div><div>Deterministic policy first · AI as analyst · human escalation by design</div></footer>
  </div>;
}

function LoadingState({ step }: { step: number }) { return <div className='loading-state'><div className='scanner'><div className='scanner-ring'/><Radar size={34}/></div><h3>{stages[Math.max(0, Math.min(stages.length - 1, step - 1))]}</h3><p>AEGIS is collecting evidence without requesting a signature.</p><div className='loading-lines'><span/><span/><span/></div></div>; }
function ResultView({ result, riskLabel, copied, onCopy }: { result: Analysis; riskLabel: string; copied: boolean; onCopy: () => void }) { return <div className='result-content'><div className={`verdict ${result.decision}`}><div className='verdict-icon'>{result.decision === 'ALLOW' ? <CheckCircle2 size={22}/> : result.decision === 'BLOCK' ? <XCircle size={22}/> : <AlertTriangle size={22}/>}</div><div><span>AEGIS DECISION</span><strong>{prettyDecision(result.decision)}</strong></div><div className='verdict-score'><strong>{result.riskScore}</strong><span>/100 RISK</span></div></div><div className='result-head'><div><span className='muted tiny'>EXPOSURE</span><h3>{riskLabel}</h3><p>{result.aiRationale}</p></div><div className='confidence'><Sparkles size={14}/><span>AI confidence</span><strong>{Math.round(result.aiConfidence * 100)}%</strong></div></div><div className='metric-grid'><Metric label='Deterministic' value={`${result.deterministicScore}/100`} icon={<Shield size={14}/>}/><Metric label='RPC' value={result.rpcStatus} icon={<Activity size={14}/>}/><Metric label='Gas' value={result.gasEstimate} icon={<TimerReset size={14}/>}/></div><div className='intel-card'><div className='intel-head'><div><span className='panel-kicker'>TRANSACTION INTELLIGENCE</span><h4>{shortAddress(result.selector)} · {result.selectorLabel}</h4></div><span className='verification'><Network size={13}/> {result.targetType}</span></div><div className='intel-grid'><Info label='Intent match' value={result.aiAlignment}/><Info label='Proxy' value={result.proxyDetected ? 'Detected' : 'No signal'}/><Info label='State probe' value={result.temporalConsistency}/><Info label='Block' value={shortAddress(result.networkBlock)}/></div></div><div className='section-label'><span>WHY</span><span>{result.findings.length} signals</span></div><div className='finding-list'>{result.findings.slice(0, 6).map((f, i) => <div className='finding' key={`${f.title}-${i}`}><span className={`sev ${f.severity}`}>{f.severity}</span><div><b>{f.title}</b><p>{f.detail}</p><small>{f.source}</small></div></div>)}</div><div className='evidence'><div><span className='panel-kicker'>DECISION FINGERPRINT</span><code>{result.evidenceHash}</code><small>MVP evidence identifier · onchain attestation is the next milestone</small></div><button className='copy-btn' onClick={onCopy}>{copied ? <Check size={14}/> : <Clipboard size={14}/>} {copied ? 'Copied' : 'Copy'}</button></div></div>; }
function Metric({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className='metric'><div>{icon}<span>{label}</span></div><strong>{value}</strong></div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><strong>{value}</strong></div>; }
function Architecture() { return <div className='architecture-layout'><section className='panel architecture-main'><div className='panel-title'><div><span className='panel-kicker'>DEFENSE IN DEPTH</span><h2>Six stages. One authority.</h2></div><span className='tag'>PRODUCT PATH</span></div><div className='architecture-flow'><Layer n='01' icon={<Fingerprint size={19}/>} title='Intent compiler' text='Turns human authorization into explicit limits and permitted effects.' tag='structured AI'/><Layer n='02' icon={<Braces size={19}/>} title='Deterministic decoder' text='Inspects calldata, approvals, value limits and known high-risk actions.' tag='no LLM'/><Layer n='03' icon={<DatabaseZap size={19}/>} title='Contract intelligence' text='Production path adds verified source, ABI resolution, proxy and delegated-account awareness.' tag='next'/><Layer n='04' icon={<Activity size={19}/>} title='Execution simulation' text='Tests the transaction against live Arbitrum state and adjacent-state sensitivity.' tag='Arbitrum'/><Layer n='05' icon={<Bot size={19}/>} title='Semantic review' text='Challenges whether the proposed effect actually matches the human intent.' tag='AI analyst'/><Layer n='06' icon={<Shield size={19}/>} title='Onchain enforcement' text='Smart-account policy becomes the final execution boundary.' tag='next milestone'/></div></section><aside className='architecture-side'><section className='panel'><span className='panel-kicker'>PRINCIPLE</span><h3 className='quote'>“Intelligence can recommend. Policy must authorize.”</h3><p className='muted architecture-copy'>El modelo no recibe autoridad unilateral para mover fondos. La política mantiene el control.</p></section><section className='panel stack-card'><div className='mini-row'><Sparkles size={17}/><div><b>AI</b><span>semantic risk</span></div></div><div className='mini-row'><Network size={17}/><div><b>Arbitrum</b><span>execution evidence</span></div></div><div className='mini-row'><Code2 size={17}/><div><b>Verified data</b><span>contract intelligence path</span></div></div><div className='mini-row'><Shield size={17}/><div><b>Smart account</b><span>enforcement target</span></div></div></section></aside></div>; }
function Opportunity() { return <div className='opportunity-grid'><section className='panel opportunity-hero'><span className='panel-kicker'>THE WEDGE</span><h2>AI agents are gaining transaction authority. AEGIS sells the boundary.</h2><p>El MVP entra como API de análisis pre-firma. El producto evoluciona hacia políticas, simulación adversarial y enforcement instalable en smart accounts.</p><div className='opportunity-metrics'><div><strong>API</strong><span>pre-sign security</span></div><div><strong>SDK</strong><span>agent permissions</span></div><div><strong>Guard</strong><span>onchain enforcement</span></div></div></section><section className='panel'><span className='panel-kicker'>INITIAL ICP</span><h3>Who pays first?</h3><div className='customer-list'><Customer title='AI wallets' text='Need bounded execution before giving an agent autonomy.'/><Customer title='Trading agents' text='Need policy limits and human escalation.'/><Customer title='Smart-account platforms' text='Need reusable transaction risk infrastructure.'/></div></section><section className='panel'><span className='panel-kicker'>MONETIZATION</span><h3>Security API → platform</h3><div className='pricing'><Price title='Developer' price='$39' suffix='/mo'/><Price title='Team' price='$249' suffix='/mo'/><Price title='Enterprise' price='$1.5k+' suffix='/mo'/></div><p className='footnote'>Pricing is an MVP hypothesis for validation, not audited revenue guidance.</p></section><section className='panel'><span className='panel-kicker'>HACKATHON STORY</span><h3>Demo in 45 seconds</h3><ol className='demo-script'><li>Agent proposes a swap.</li><li>Transaction requests an excessive approval.</li><li>AEGIS compares intent and transaction evidence.</li><li>Simulation and AI explain the mismatch.</li><li>Policy returns <b>BLOCK / HUMAN REVIEW</b>.</li></ol></section></div>; }
function Layer({ n, icon, title, text, tag }: { n: string; icon: React.ReactNode; title: string; text: string; tag: string }) { return <div className='layer'><div className='layer-number'>{n}</div><div className='layer-icon'>{icon}</div><div className='layer-copy'><h4>{title}</h4><p>{text}</p></div><span className='tag'>{tag}</span></div>; }
function Customer({ title, text }: { title: string; text: string }) { return <div className='customer'><div className='customer-icon'><Bot size={15}/></div><div><b>{title}</b><p>{text}</p></div><ExternalLink size={13}/></div>; }
function Price({ title, price, suffix }: { title: string; price: string; suffix: string }) { return <div className='price-card'><CircleDollarSign size={16}/><span>{title}</span><div><strong>{price}</strong><small>{suffix}</small></div></div>; }
